#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

echo -e "${RED}Cleaning repo${NC}"

find . -type f \( -name "*~" -o -name "*.gcda" -o -name "*.gcno" -o -name "#*#" -o -name "*.out" -o -name "*.hi" -o -name "*.o" \) -delete