#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

if [ ! $1 ]
then
    echo -e "${RED}nothing${NC}"
else
    echo -e "${GREEN}Creating $1 files${NC}"
    for i in `seq 1 $1`;
        do
            if [ -d ex_0$1 ]
            then
                continue
            else
                if [ $i -lt 10 ]
                then
                    touch ex_0$i
                else
                    touch ex_$i
                fi
            fi
    done
fi