#!/bin/bash

if [ ! $# -gt 0 ]
then
    echo "Give a commit message"
else
    echo "Cleaning repo"
    find . -type f \( -name "*~" -o -name "*.gcda" -o -name "*.gcno" -o -name "#*#" \) -delete
    echo "Adding files"
    git add .
    echo "Commit changes"
    git commit -m $1
    echo "Pushing my work"
    git push origin main
    echo "Listing files"
    git ls-files
fi